### ISSUE TITLE
Unsupported operation infinity or Nan to Int when set elevation to 0.0

### ISSUE THREAD

**Issue by MirzaUkas** [MayLau-CbL/flutter_horizontal_data_table#12] opened 2020-10-15 09:21 UTC
![image](https://user-images.githubusercontent.com/22706639/96103962-79a2dd80-0f02-11eb-97e2-a641f6d760e4.png)

**Comment by MayLau-CbL** [comment] 2020-10-24 05:05
@MirzaUkas would you mind giving me a simple example that may repeat that error and what the testing device of the app (android, ios or web) is using as I cannot repeat the issue.

**Comment by MirzaUkas** [comment] 2020-11-11 03:52
@MayLau-CbL Thanks for the response, this is my example widget
`HorizontalDataTable(
        leftHandSideColumnWidth: widget.leftColumnWidth,
        rightHandSideColumnWidth: widget.rightColumnWidth,
        isFixedHeader: true,
        elevation: 0.0,
        elevationColor: Colors.white,
        headerWidgets: _getTitleWidget(),
        leftSideItemBuilder: _generateFirstColumnRow,
        rightSideItemBuilder: _generateRightHandSideColumnRow,
        itemCount: widget.data.length,
      )`
when i set elevation to 0.0 the table show error like the error message above. I used this table on the android btw.

**Comment by Kobatsu** [comment] 2020-11-12 14:01
I have the same problem, there seems to be a division by zero in the method `_getRightSideHeaderScrollColumn()` :
``` dart
return Container(
              decoration: BoxDecoration(
                color: widget.rightHandSideColBackgroundColor,
                boxShadow: [
                  BoxShadow(
                    color: widget.elevationColor.withAlpha((10 *
                            (_getElevation(verticalOffset) / widget.elevation))
                        .toInt()),
                    blurRadius: 0.0,
                    // has the effect of softening the shadow
                    spreadRadius: 0.0,
                    // has the effect of extending the shadow
                    offset: Offset(
                      0.0, // horizontal, move right 10
                      _getElevation(verticalOffset), // vertical, move down 10
                    ),
                  )
                ],
              ),
              child: child,
//                elevation: _getElevation(verticalOffset)
            )
```

Note the line with the shadowColor : `color: widget.elevationColor.withAlpha((10 *
                            (_getElevation(verticalOffset) / widget.elevation))
                        .toInt())`

**Comment by MayLau-CbL** [comment] 2020-11-12 14:13
Thank you for the information! I will take a look this weekend.🙂

**Comment by MayLau-CbL** [comment] 2020-11-13 15:08
@MirzaUkas and @Kobatsu , I updated the new version v1.0.8 fixed the elevation zero issue.
And thank you @Kobatsu , as you mention, the cause of the issue is due to the infinite number.
I will close this issue first, if there is any problem please let me know to re-open it. :-)

**Closed by MayLau-CbL** 2020-11-13 15:08 UTC
